# 贝叶斯优化参数
ref_point: [180, 0, 0.6, 0.15, 87, 18, 0.475, 0.627, 0.171, 14.001, 0.9501]  # 参考点
n_iter: 15                  # 优化迭代次数
batch_size: 3                # 每批评估数量
num_restarts: 20             # 优化重启次数
raw_samples: 512             # 初始采样数
hv_improve_tol: 1e-4         # HV改进容忍度


# 模型参数
model:
  lengthscale_prior: [0.1, 1.0]  # 长度尺度先验
  noise_prior: [0.001, 0.1]      # 噪声先验

