# 遗传算法基础参数
pop_size: 200   # 种群大小
n_gen: 100      # 进化代数


# 交叉算子配置
crossover:
  prob: 0.9    # 交叉概率
  eta: 15      # 分布指数

# 变异算子配置
mutation:
  prob: 0.3    # 变异概率
  eta: 20      # 分布指数

# 其他参数
sampling: Dirichlet

ref_point: [180, 0, 0.6, 0.15, 87, 18, 0.475, 0.627, 0.171, 14.001, 0.9501]  # 参考点
